# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='zipcode',
        ),
    ]
