# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbView', '0002_remove_exercise_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='activityType',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficultyrating',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
