all:
	g++ -std=c++0x -o Cult driver.cpp dead.cpp dead.hpp dorm.cpp dorm.hpp feast.cpp feast.hpp green.cpp green.hpp hallway.cpp hallway.hpp item.cpp item.hpp mud.cpp mud.hpp player.cpp player.hpp receivery.cpp receivery.hpp relax.cpp relax.hpp rock.cpp rock.hpp room.cpp room.hpp text.cpp text.hpp
clean:

	$(RM) Cult